CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_POINTING=y
CONFIG_IQS7211E=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y


# REQUIRED: Enable the acceleration module
CONFIG_ZMK_INPUT_PROCESSOR_ACCELERATION=y


# Choose your level (1 or 2)
CONFIG_INPUT_PROCESSOR_ACCEL_LEVEL_SIMPLE=y      # Level 1: Simple
# CONFIG_INPUT_PROCESSOR_ACCEL_LEVEL_STANDARD=y  # Level 2: Standard

# Office Presets:
# CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_OFFICE_OPTICAL=y     # Optical mouse (800 DPI)
CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_OFFICE_TRACKPAD=y    # Trackpad (1000 DPI)
